### ISSUE TITLE
To-do: Dev

### ISSUE THREAD

**Issue by mmarol** [mmarol/sankalpana#1]
- [ ] Switch the Homepage and Events page from the 2-column to a 1-column layout
- [ ] With all the 1-column layout pages, restrict the size of the thumbnail to a specific aspect ratio
- [ ] Remove the Announcements post-type from the backend, as Events will take care of this content
- [ ] Have the Homepage collect upcoming events as well as upcoming classes. These will be ordered chronologically, newest to oldest
- [ ] Indicate whether an event is an upcoming or past event on the Events page
- [ ] Reduce the amount of space that the yellow intro/title bars take by either reducing the size of the text or the spacing around the text
- [ ] Pull in an example of a textural video element for the Homepage to show you how it will feel in place of the YouTube video
- [ ] Move the Event details and registration button below the text on the Event detail pages
- [ ] Remove the text field that's above the form on the contact page
- [ ] Start building out the srinivasreddy.org site
- [ ] Add the ability on the srinivasreddy.org site to upload pdfs of articles in addition to being able to link to live articles on other websites
